sudo: required
dist: trusty

ddons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - boost-devel-1.57

language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ../

script: make brewer