sudo: required
dist: trusty

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-all-dev

language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ../

script:
  - make
  - ./test/test_brewer
